# theme: jekyll-theme-minimal
theme:
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
title: Chihiro Taguchi
author: Chihiro Taguchi
logo: /assets/img/portrait.jpg
description: Photo by Kamolchanok Sarisuta.
# google_analytics: G-M5THZQG7L5
google_analytics: G-QJKV1WYSMW